// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.






function findNext(x, val,z){
  if (x === 1){
    return 1;
  }
  if (x === 0){
      return 1;
  }
  a[x] =  (findNext(x-1, val) + findNext(x-2, val));
  return a[x];
}

function evenFib(top){

}
var a = [];
a[0] = 0;
a[1] = 1;


console.log(findNext(32,0,a));
a = a.filter(function(n) { return n % 2 === 0;});
console.log(a.reduce(function(a,b){
  return a + b;}
));
